[supabase]
url = "https://tntllfyftxjjxgcsulpv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudGxsZnlmdHhqanhnY3N1bHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxOTEzMDYsImV4cCI6MjA4Mjc2NzMwNn0.tfs4bbhnaKAW94Xt1Ata3Q7q5cesIQ6RboTwFkGTJHM"